In [3]:
import torch
from torch.nn import Linear

In [4]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [7]:
x = torch.tensor([[0.0]])

In [8]:
yhat = model(x)

In [9]:
yhat

tensor([[-0.4414]], grad_fn=<AddmmBackward0>)

In [13]:
# Create a customized linear

class linear_regression(torch.nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = torch.nn.Linear(input_size, output_size)
        
    # Prediction
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [14]:
# Create the linear regression model and print the parameters

model = linear_regression(2,1)
print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[-0.1371,  0.3319]], requires_grad=True), Parameter containing:
tensor([-0.6657], requires_grad=True)]
