In [1]:
import torch

In [2]:
a = [[11,12,13], [21,22,23], [31,32,33]]

In [3]:
A = torch.tensor(a)

In [5]:
A.ndimension() # aka Rank

2

In [7]:
A.shape

torch.Size([3, 3])

In [9]:
# Vertical axis is 0, horizontal axis is 1
# row, column

In [10]:
B = A*2

In [11]:
B

tensor([[22, 24, 26],
        [42, 44, 46],
        [62, 64, 66]])

In [12]:
# Lab 2

In [13]:
a = torch.tensor([[0,1,1],[1,0,1]])

In [14]:
a.size()

torch.Size([2, 3])

In [15]:
a.ndimension()

2

In [17]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y

    

In [18]:
X_times_Y

tensor([[2, 0],
        [0, 2]])

In [19]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)

In [20]:
A_times_B

tensor([[0, 2],
        [0, 2]])